# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/eaget-4tb/data/llm_server/lmdeploy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/eaget-4tb/data/llm_server/lmdeploy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cpack --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Devel\" \"Unspecified\" \"fmt-core\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/oliveagle/.local/lib/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/eaget-4tb/data/llm_server/lmdeploy/CMakeFiles /mnt/eaget-4tb/data/llm_server/lmdeploy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/eaget-4tb/data/llm_server/lmdeploy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /mnt/eaget-4tb/data/llm_server/lmdeploy/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f _deps/fmt-build/CMakeFiles/fmt.dir/build.make _deps/fmt-build/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named cutlass_docs

# Build rule for target.
cutlass_docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cutlass_docs
.PHONY : cutlass_docs

# fast build rule for target.
cutlass_docs/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/cutlass_docs.dir/build.make _deps/repo-cutlass-build/CMakeFiles/cutlass_docs.dir/build
.PHONY : cutlass_docs/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/Experimental.dir/build.make _deps/repo-cutlass-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/Nightly.dir/build.make _deps/repo-cutlass-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/Continuous.dir/build.make _deps/repo-cutlass-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/repo-cutlass-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/NightlyStart.dir/build.make _deps/repo-cutlass-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/repo-cutlass-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/repo-cutlass-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/NightlyBuild.dir/build.make _deps/repo-cutlass-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/NightlyTest.dir/build.make _deps/repo-cutlass-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/repo-cutlass-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/repo-cutlass-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/NightlySubmit.dir/build.make _deps/repo-cutlass-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ContinuousStart.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ContinuousTest.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/repo-cutlass-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named test_all

# Build rule for target.
test_all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_all
.PHONY : test_all

# fast build rule for target.
test_all/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-cutlass-build/CMakeFiles/test_all.dir/build.make _deps/repo-cutlass-build/CMakeFiles/test_all.dir/build
.PHONY : test_all/fast

#=============================================================================
# Target rules for targets named yaml-cpp

# Build rule for target.
yaml-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp
.PHONY : yaml-cpp

# fast build rule for target.
yaml-cpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/build.make _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/build
.PHONY : yaml-cpp/fast

#=============================================================================
# Target rules for targets named yaml-cpp-sandbox

# Build rule for target.
yaml-cpp-sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-sandbox
.PHONY : yaml-cpp-sandbox

# fast build rule for target.
yaml-cpp-sandbox/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox.dir/build
.PHONY : yaml-cpp-sandbox/fast

#=============================================================================
# Target rules for targets named yaml-cpp-parse

# Build rule for target.
yaml-cpp-parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-parse
.PHONY : yaml-cpp-parse

# fast build rule for target.
yaml-cpp-parse/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse.dir/build
.PHONY : yaml-cpp-parse/fast

#=============================================================================
# Target rules for targets named yaml-cpp-read

# Build rule for target.
yaml-cpp-read: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-read
.PHONY : yaml-cpp-read

# fast build rule for target.
yaml-cpp-read/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read.dir/build
.PHONY : yaml-cpp-read/fast

#=============================================================================
# Target rules for targets named xgrammar

# Build rule for target.
xgrammar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xgrammar
.PHONY : xgrammar

# fast build rule for target.
xgrammar/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xgrammar-build/CMakeFiles/xgrammar.dir/build.make _deps/xgrammar-build/CMakeFiles/xgrammar.dir/build
.PHONY : xgrammar/fast

#=============================================================================
# Target rules for targets named turbomind

# Build rule for target.
turbomind: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 turbomind
.PHONY : turbomind

# fast build rule for target.
turbomind/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/CMakeFiles/turbomind.dir/build.make src/turbomind/CMakeFiles/turbomind.dir/build
.PHONY : turbomind/fast

#=============================================================================
# Target rules for targets named cuda_utils

# Build rule for target.
cuda_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuda_utils
.PHONY : cuda_utils

# fast build rule for target.
cuda_utils/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/utils/CMakeFiles/cuda_utils.dir/build.make src/turbomind/utils/CMakeFiles/cuda_utils.dir/build
.PHONY : cuda_utils/fast

#=============================================================================
# Target rules for targets named nvtx_utils

# Build rule for target.
nvtx_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvtx_utils
.PHONY : nvtx_utils

# fast build rule for target.
nvtx_utils/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/utils/CMakeFiles/nvtx_utils.dir/build.make src/turbomind/utils/CMakeFiles/nvtx_utils.dir/build
.PHONY : nvtx_utils/fast

#=============================================================================
# Target rules for targets named memory_utils

# Build rule for target.
memory_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memory_utils
.PHONY : memory_utils

# fast build rule for target.
memory_utils/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/utils/CMakeFiles/memory_utils.dir/build.make src/turbomind/utils/CMakeFiles/memory_utils.dir/build
.PHONY : memory_utils/fast

#=============================================================================
# Target rules for targets named anomaly_handler

# Build rule for target.
anomaly_handler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 anomaly_handler
.PHONY : anomaly_handler

# fast build rule for target.
anomaly_handler/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/utils/CMakeFiles/anomaly_handler.dir/build.make src/turbomind/utils/CMakeFiles/anomaly_handler.dir/build
.PHONY : anomaly_handler/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/utils/CMakeFiles/parser.dir/build.make src/turbomind/utils/CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named weight_serializer

# Build rule for target.
weight_serializer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 weight_serializer
.PHONY : weight_serializer

# fast build rule for target.
weight_serializer/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/utils/CMakeFiles/weight_serializer.dir/build.make src/turbomind/utils/CMakeFiles/weight_serializer.dir/build
.PHONY : weight_serializer/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/core/CMakeFiles/core.dir/build.make src/turbomind/core/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named ban_bad_words

# Build rule for target.
ban_bad_words: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ban_bad_words
.PHONY : ban_bad_words

# fast build rule for target.
ban_bad_words/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/ban_bad_words.dir/build.make src/turbomind/kernels/CMakeFiles/ban_bad_words.dir/build
.PHONY : ban_bad_words/fast

#=============================================================================
# Target rules for targets named stop_criteria

# Build rule for target.
stop_criteria: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stop_criteria
.PHONY : stop_criteria

# fast build rule for target.
stop_criteria/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/stop_criteria.dir/build.make src/turbomind/kernels/CMakeFiles/stop_criteria.dir/build
.PHONY : stop_criteria/fast

#=============================================================================
# Target rules for targets named activation_kernels

# Build rule for target.
activation_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 activation_kernels
.PHONY : activation_kernels

# fast build rule for target.
activation_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/activation_kernels.dir/build.make src/turbomind/kernels/CMakeFiles/activation_kernels.dir/build
.PHONY : activation_kernels/fast

#=============================================================================
# Target rules for targets named activation

# Build rule for target.
activation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 activation
.PHONY : activation

# fast build rule for target.
activation/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/activation.dir/build.make src/turbomind/kernels/CMakeFiles/activation.dir/build
.PHONY : activation/fast

#=============================================================================
# Target rules for targets named quantization_kernels

# Build rule for target.
quantization_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quantization_kernels
.PHONY : quantization_kernels

# fast build rule for target.
quantization_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/quantization_kernels.dir/build.make src/turbomind/kernels/CMakeFiles/quantization_kernels.dir/build
.PHONY : quantization_kernels/fast

#=============================================================================
# Target rules for targets named logprob_kernels

# Build rule for target.
logprob_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logprob_kernels
.PHONY : logprob_kernels

# fast build rule for target.
logprob_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/logprob_kernels.dir/build.make src/turbomind/kernels/CMakeFiles/logprob_kernels.dir/build
.PHONY : logprob_kernels/fast

#=============================================================================
# Target rules for targets named unfused_attention_kernels

# Build rule for target.
unfused_attention_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unfused_attention_kernels
.PHONY : unfused_attention_kernels

# fast build rule for target.
unfused_attention_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/unfused_attention_kernels.dir/build.make src/turbomind/kernels/CMakeFiles/unfused_attention_kernels.dir/build
.PHONY : unfused_attention_kernels/fast

#=============================================================================
# Target rules for targets named decoding_kernels

# Build rule for target.
decoding_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 decoding_kernels
.PHONY : decoding_kernels

# fast build rule for target.
decoding_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/decoding_kernels.dir/build.make src/turbomind/kernels/CMakeFiles/decoding_kernels.dir/build
.PHONY : decoding_kernels/fast

#=============================================================================
# Target rules for targets named gpt_kernels

# Build rule for target.
gpt_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpt_kernels
.PHONY : gpt_kernels

# fast build rule for target.
gpt_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/gpt_kernels.dir/build.make src/turbomind/kernels/CMakeFiles/gpt_kernels.dir/build
.PHONY : gpt_kernels/fast

#=============================================================================
# Target rules for targets named sampling_topk_kernels

# Build rule for target.
sampling_topk_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sampling_topk_kernels
.PHONY : sampling_topk_kernels

# fast build rule for target.
sampling_topk_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/sampling_topk_kernels.dir/build.make src/turbomind/kernels/CMakeFiles/sampling_topk_kernels.dir/build
.PHONY : sampling_topk_kernels/fast

#=============================================================================
# Target rules for targets named sampling_topp_kernels

# Build rule for target.
sampling_topp_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sampling_topp_kernels
.PHONY : sampling_topp_kernels

# fast build rule for target.
sampling_topp_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/sampling_topp_kernels.dir/build.make src/turbomind/kernels/CMakeFiles/sampling_topp_kernels.dir/build
.PHONY : sampling_topp_kernels/fast

#=============================================================================
# Target rules for targets named sampling_penalty_kernels

# Build rule for target.
sampling_penalty_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sampling_penalty_kernels
.PHONY : sampling_penalty_kernels

# fast build rule for target.
sampling_penalty_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/sampling_penalty_kernels.dir/build.make src/turbomind/kernels/CMakeFiles/sampling_penalty_kernels.dir/build
.PHONY : sampling_penalty_kernels/fast

#=============================================================================
# Target rules for targets named sampling_kernels

# Build rule for target.
sampling_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sampling_kernels
.PHONY : sampling_kernels

# fast build rule for target.
sampling_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/sampling_kernels.dir/build.make src/turbomind/kernels/CMakeFiles/sampling_kernels.dir/build
.PHONY : sampling_kernels/fast

#=============================================================================
# Target rules for targets named apply_token_bitmask_inplace_cuda

# Build rule for target.
apply_token_bitmask_inplace_cuda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 apply_token_bitmask_inplace_cuda
.PHONY : apply_token_bitmask_inplace_cuda

# fast build rule for target.
apply_token_bitmask_inplace_cuda/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/CMakeFiles/apply_token_bitmask_inplace_cuda.dir/build.make src/turbomind/kernels/CMakeFiles/apply_token_bitmask_inplace_cuda.dir/build
.PHONY : apply_token_bitmask_inplace_cuda/fast

#=============================================================================
# Target rules for targets named attention

# Build rule for target.
attention: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 attention
.PHONY : attention

# fast build rule for target.
attention/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/attention/CMakeFiles/attention.dir/build.make src/turbomind/kernels/attention/CMakeFiles/attention.dir/build
.PHONY : attention/fast

#=============================================================================
# Target rules for targets named attention_kernels

# Build rule for target.
attention_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 attention_kernels
.PHONY : attention_kernels

# fast build rule for target.
attention_kernels/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/attention/kernel/CMakeFiles/attention_kernels.dir/build.make src/turbomind/kernels/attention/kernel/CMakeFiles/attention_kernels.dir/build
.PHONY : attention_kernels/fast

#=============================================================================
# Target rules for targets named gemm2

# Build rule for target.
gemm2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm2
.PHONY : gemm2

# fast build rule for target.
gemm2/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/gemm/CMakeFiles/gemm2.dir/build.make src/turbomind/kernels/gemm/CMakeFiles/gemm2.dir/build
.PHONY : gemm2/fast

#=============================================================================
# Target rules for targets named gemm2_sm90

# Build rule for target.
gemm2_sm90: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm2_sm90
.PHONY : gemm2_sm90

# fast build rule for target.
gemm2_sm90/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/gemm/CMakeFiles/gemm2_sm90.dir/build.make src/turbomind/kernels/gemm/CMakeFiles/gemm2_sm90.dir/build
.PHONY : gemm2_sm90/fast

#=============================================================================
# Target rules for targets named rms_norm

# Build rule for target.
rms_norm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rms_norm
.PHONY : rms_norm

# fast build rule for target.
rms_norm/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/kernels/norm/CMakeFiles/rms_norm.dir/build.make src/turbomind/kernels/norm/CMakeFiles/rms_norm.dir/build
.PHONY : rms_norm/fast

#=============================================================================
# Target rules for targets named host_comm

# Build rule for target.
host_comm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 host_comm
.PHONY : host_comm

# fast build rule for target.
host_comm/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/comm/CMakeFiles/host_comm.dir/build.make src/turbomind/comm/CMakeFiles/host_comm.dir/build
.PHONY : host_comm/fast

#=============================================================================
# Target rules for targets named device_comm

# Build rule for target.
device_comm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 device_comm
.PHONY : device_comm

# fast build rule for target.
device_comm/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/comm/CMakeFiles/device_comm.dir/build.make src/turbomind/comm/CMakeFiles/device_comm.dir/build
.PHONY : device_comm/fast

#=============================================================================
# Target rules for targets named cuda_ipc_comm

# Build rule for target.
cuda_ipc_comm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuda_ipc_comm
.PHONY : cuda_ipc_comm

# fast build rule for target.
cuda_ipc_comm/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/comm/cuda_ipc/CMakeFiles/cuda_ipc_comm.dir/build.make src/turbomind/comm/cuda_ipc/CMakeFiles/cuda_ipc_comm.dir/build
.PHONY : cuda_ipc_comm/fast

#=============================================================================
# Target rules for targets named gloo_comm

# Build rule for target.
gloo_comm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gloo_comm
.PHONY : gloo_comm

# fast build rule for target.
gloo_comm/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/comm/gloo/CMakeFiles/gloo_comm.dir/build.make src/turbomind/comm/gloo/CMakeFiles/gloo_comm.dir/build
.PHONY : gloo_comm/fast

#=============================================================================
# Target rules for targets named test_ipc_comm

# Build rule for target.
test_ipc_comm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ipc_comm
.PHONY : test_ipc_comm

# fast build rule for target.
test_ipc_comm/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/comm/gloo/CMakeFiles/test_ipc_comm.dir/build.make src/turbomind/comm/gloo/CMakeFiles/test_ipc_comm.dir/build
.PHONY : test_ipc_comm/fast

#=============================================================================
# Target rules for targets named gloo

# Build rule for target.
gloo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gloo
.PHONY : gloo

# fast build rule for target.
gloo/fast:
	$(MAKE) $(MAKESILENT) -f _deps/gloo-build/gloo/CMakeFiles/gloo.dir/build.make _deps/gloo-build/gloo/CMakeFiles/gloo.dir/build
.PHONY : gloo/fast

#=============================================================================
# Target rules for targets named guided_decoding

# Build rule for target.
guided_decoding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 guided_decoding
.PHONY : guided_decoding

# fast build rule for target.
guided_decoding/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/generation/CMakeFiles/guided_decoding.dir/build.make src/turbomind/generation/CMakeFiles/guided_decoding.dir/build
.PHONY : guided_decoding/fast

#=============================================================================
# Target rules for targets named generation

# Build rule for target.
generation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generation
.PHONY : generation

# fast build rule for target.
generation/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/generation/CMakeFiles/generation.dir/build.make src/turbomind/generation/CMakeFiles/generation.dir/build
.PHONY : generation/fast

#=============================================================================
# Target rules for targets named models

# Build rule for target.
models: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 models
.PHONY : models

# fast build rule for target.
models/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/models/CMakeFiles/models.dir/build.make src/turbomind/models/CMakeFiles/models.dir/build
.PHONY : models/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/engine/CMakeFiles/engine.dir/build.make src/turbomind/engine/CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named _turbomind

# Build rule for target.
_turbomind: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _turbomind
.PHONY : _turbomind

# fast build rule for target.
_turbomind/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/python/CMakeFiles/_turbomind.dir/build.make src/turbomind/python/CMakeFiles/_turbomind.dir/build
.PHONY : _turbomind/fast

#=============================================================================
# Target rules for targets named _xgrammar

# Build rule for target.
_xgrammar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _xgrammar
.PHONY : _xgrammar

# fast build rule for target.
_xgrammar/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/python/CMakeFiles/_xgrammar.dir/build.make src/turbomind/python/CMakeFiles/_xgrammar.dir/build
.PHONY : _xgrammar/fast

#=============================================================================
# Target rules for targets named turbomind_c

# Build rule for target.
turbomind_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 turbomind_c
.PHONY : turbomind_c

# fast build rule for target.
turbomind_c/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/capi/CMakeFiles/turbomind_c.dir/build.make src/turbomind/capi/CMakeFiles/turbomind_c.dir/build
.PHONY : turbomind_c/fast

#=============================================================================
# Target rules for targets named test_initfrompath_stepby

# Build rule for target.
test_initfrompath_stepby: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_initfrompath_stepby
.PHONY : test_initfrompath_stepby

# fast build rule for target.
test_initfrompath_stepby/fast:
	$(MAKE) $(MAKESILENT) -f src/turbomind/capi/CMakeFiles/test_initfrompath_stepby.dir/build.make src/turbomind/capi/CMakeFiles/test_initfrompath_stepby.dir/build
.PHONY : test_initfrompath_stepby/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... cutlass_docs"
	@echo "... test_all"
	@echo "... _turbomind"
	@echo "... _xgrammar"
	@echo "... activation"
	@echo "... activation_kernels"
	@echo "... anomaly_handler"
	@echo "... apply_token_bitmask_inplace_cuda"
	@echo "... attention"
	@echo "... attention_kernels"
	@echo "... ban_bad_words"
	@echo "... core"
	@echo "... cuda_ipc_comm"
	@echo "... cuda_utils"
	@echo "... decoding_kernels"
	@echo "... device_comm"
	@echo "... engine"
	@echo "... fmt"
	@echo "... gemm2"
	@echo "... gemm2_sm90"
	@echo "... generation"
	@echo "... gloo"
	@echo "... gloo_comm"
	@echo "... gpt_kernels"
	@echo "... guided_decoding"
	@echo "... host_comm"
	@echo "... logprob_kernels"
	@echo "... memory_utils"
	@echo "... models"
	@echo "... nvtx_utils"
	@echo "... parser"
	@echo "... quantization_kernels"
	@echo "... rms_norm"
	@echo "... sampling_kernels"
	@echo "... sampling_penalty_kernels"
	@echo "... sampling_topk_kernels"
	@echo "... sampling_topp_kernels"
	@echo "... stop_criteria"
	@echo "... test_initfrompath_stepby"
	@echo "... test_ipc_comm"
	@echo "... turbomind"
	@echo "... turbomind_c"
	@echo "... unfused_attention_kernels"
	@echo "... weight_serializer"
	@echo "... xgrammar"
	@echo "... yaml-cpp"
	@echo "... yaml-cpp-parse"
	@echo "... yaml-cpp-read"
	@echo "... yaml-cpp-sandbox"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /mnt/eaget-4tb/data/llm_server/lmdeploy/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

