# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lmdeploy_pb2 as lmdeploy__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lmdeploy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LMDeployServiceStub(object):
    """LMDeploy gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/lmdeploy.v1.LMDeployService/Generate',
                request_serializer=lmdeploy__pb2.GenerateRequest.SerializeToString,
                response_deserializer=lmdeploy__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GenerateStream = channel.unary_stream(
                '/lmdeploy.v1.LMDeployService/GenerateStream',
                request_serializer=lmdeploy__pb2.GenerateRequest.SerializeToString,
                response_deserializer=lmdeploy__pb2.GenerateStreamResponse.FromString,
                _registered_method=True)
        self.GenerateBidirectional = channel.stream_stream(
                '/lmdeploy.v1.LMDeployService/GenerateBidirectional',
                request_serializer=lmdeploy__pb2.GenerateRequest.SerializeToString,
                response_deserializer=lmdeploy__pb2.GenerateStreamResponse.FromString,
                _registered_method=True)
        self.GenerateBatch = channel.unary_unary(
                '/lmdeploy.v1.LMDeployService/GenerateBatch',
                request_serializer=lmdeploy__pb2.BatchGenerateRequest.SerializeToString,
                response_deserializer=lmdeploy__pb2.BatchGenerateResponse.FromString,
                _registered_method=True)
        self.Tokenize = channel.unary_unary(
                '/lmdeploy.v1.LMDeployService/Tokenize',
                request_serializer=lmdeploy__pb2.TokenizeRequest.SerializeToString,
                response_deserializer=lmdeploy__pb2.TokenizeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/lmdeploy.v1.LMDeployService/Health',
                request_serializer=lmdeploy__pb2.HealthRequest.SerializeToString,
                response_deserializer=lmdeploy__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ModelInfo = channel.unary_unary(
                '/lmdeploy.v1.LMDeployService/ModelInfo',
                request_serializer=lmdeploy__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=lmdeploy__pb2.ModelInfoResponse.FromString,
                _registered_method=True)


class LMDeployServiceServicer(object):
    """LMDeploy gRPC service definition
    """

    def Generate(self, request, context):
        """Non-streaming inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStream(self, request, context):
        """Streaming inference (server-side streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateBidirectional(self, request_iterator, context):
        """Bidirectional streaming (client sends prompts, server streams responses)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateBatch(self, request, context):
        """Batch inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tokenize(self, request, context):
        """Tokenize only (for caching)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModelInfo(self, request, context):
        """Model info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LMDeployServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=lmdeploy__pb2.GenerateRequest.FromString,
                    response_serializer=lmdeploy__pb2.GenerateResponse.SerializeToString,
            ),
            'GenerateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=lmdeploy__pb2.GenerateRequest.FromString,
                    response_serializer=lmdeploy__pb2.GenerateStreamResponse.SerializeToString,
            ),
            'GenerateBidirectional': grpc.stream_stream_rpc_method_handler(
                    servicer.GenerateBidirectional,
                    request_deserializer=lmdeploy__pb2.GenerateRequest.FromString,
                    response_serializer=lmdeploy__pb2.GenerateStreamResponse.SerializeToString,
            ),
            'GenerateBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateBatch,
                    request_deserializer=lmdeploy__pb2.BatchGenerateRequest.FromString,
                    response_serializer=lmdeploy__pb2.BatchGenerateResponse.SerializeToString,
            ),
            'Tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.Tokenize,
                    request_deserializer=lmdeploy__pb2.TokenizeRequest.FromString,
                    response_serializer=lmdeploy__pb2.TokenizeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=lmdeploy__pb2.HealthRequest.FromString,
                    response_serializer=lmdeploy__pb2.HealthResponse.SerializeToString,
            ),
            'ModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelInfo,
                    request_deserializer=lmdeploy__pb2.ModelInfoRequest.FromString,
                    response_serializer=lmdeploy__pb2.ModelInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lmdeploy.v1.LMDeployService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lmdeploy.v1.LMDeployService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LMDeployService(object):
    """LMDeploy gRPC service definition
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lmdeploy.v1.LMDeployService/Generate',
            lmdeploy__pb2.GenerateRequest.SerializeToString,
            lmdeploy__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lmdeploy.v1.LMDeployService/GenerateStream',
            lmdeploy__pb2.GenerateRequest.SerializeToString,
            lmdeploy__pb2.GenerateStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateBidirectional(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/lmdeploy.v1.LMDeployService/GenerateBidirectional',
            lmdeploy__pb2.GenerateRequest.SerializeToString,
            lmdeploy__pb2.GenerateStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lmdeploy.v1.LMDeployService/GenerateBatch',
            lmdeploy__pb2.BatchGenerateRequest.SerializeToString,
            lmdeploy__pb2.BatchGenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lmdeploy.v1.LMDeployService/Tokenize',
            lmdeploy__pb2.TokenizeRequest.SerializeToString,
            lmdeploy__pb2.TokenizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lmdeploy.v1.LMDeployService/Health',
            lmdeploy__pb2.HealthRequest.SerializeToString,
            lmdeploy__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lmdeploy.v1.LMDeployService/ModelInfo',
            lmdeploy__pb2.ModelInfoRequest.SerializeToString,
            lmdeploy__pb2.ModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
